### ISSUE TITLE
Error in Install access_restricted

### ISSUE THREAD

**Issue by rodriguesraphael** [it-projects-llc/access-addons#76]
Erro:
Odoo Server Error
```

Traceback (most recent call last):
  File "/home/raphael/odoo11/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/raphael/odoo11/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/raphael/odoo11/odoo/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/raphael/odoo11/odoo/odoo/addons/base/res/res_users.py", line 690, in create
    self._update_user_groups_view()
  File "/home/raphael/odoo11/access-addons/access_restricted/models/res_users.py", line 37, in _update_user_groups_view
    self.env['ir.config_parameter'].sudo().set_param(IR_CONFIG_NAME, real_uid)
  File "/home/raphael/odoo11/odoo-saas-tools/saas_portal/models/ir_config_parameter.py", line 19, in set_param
    return super(IrConfigParameter, self).set_param(key, value, groups=groups)
TypeError: set_param() got an unexpected keyword argument 'groups'

```
During handling of the above exception, another exception occurred:
```

Traceback (most recent call last):
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/raphael/odoo11/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/raphael/odoo11/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/raphael/odoo11/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/raphael/odoo11/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/raphael/odoo11/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/raphael/odoo11/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/raphael/odoo11/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/home/raphael/odoo11/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/raphael/odoo11/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/raphael/odoo11/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/raphael/odoo11/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/raphael/odoo11/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/raphael/odoo11/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/raphael/odoo11/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/raphael/odoo11/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/raphael/odoo11/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/raphael/odoo11/odoo/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/raphael/odoo11/odoo/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/home/raphael/odoo11/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/raphael/odoo11/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/raphael/odoo11/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/raphael/odoo11/odoo/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/home/raphael/odoo11/odoo/odoo/addons/base/res/res_users.py", line 690, in create
    self._update_user_groups_view()
  File "/home/raphael/odoo11/access-addons/access_restricted/models/res_users.py", line 37, in _update_user_groups_view
    self.env['ir.config_parameter'].sudo().set_param(IR_CONFIG_NAME, real_uid)
  File "/home/raphael/odoo11/odoo-saas-tools/saas_portal/models/ir_config_parameter.py", line 19, in set_param
    return super(IrConfigParameter, self).set_param(key, value, groups=groups)
odoo.tools.convert.ParseError: "set_param() got an unexpected keyword argument 'groups'" while parsing /home/raphael/odoo11/access-addons/access_restricted/security/access_restricted_security.xml:3, near
<record id="group_allow_add_implied_from_settings" model="res.groups">
    <field name="name">Allow add implied groups from settings</field>
  </record>
```

**Comment by yelizariev** [comment]
It's a problem of ``saas_portal`` module
